name: Anguler

on:
  workflow_dispatch:

jobs:
    uses: actions/checkout@v7.0.0 
    First:
      name: install_angular
      uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with: v1.0.0
        
  
      
    
